### ISSUE TITLE
MultiSig/Minting testing

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#100]
@KubqoA  whats the version to use with the ledger right now to test the multisig/minting support? i tried your branch and also the versions of the cardano-app (3.0.0). but when i try the following i get an error about the app-version:
```console
$ cardano-hw-cli address key-gen --path 1855H/1815H/0H --verification-key-file mint-hw.vkey --hw-signing-file mint-hw.hwsfile
Error: Device app version unsupported. Please upgrade to 2.4.

$ cardano-hw-cli version
Cardano HW CLI Tool version 1.7.0-rc0
Commit hash: 23406fe8c4e58e83e166b44be102a902a9ae4938

$ cardano-hw-cli device version
Ledger app version 3.0.0

```

**Comment by KubqoA** [comment]
Hi, it should be this PR: #98, but it seems you got that right according to the commit hash. Can I ask how did you build the tool, it seems to me that the issue is in the [`ledgerjs-cardano-shelley`](https://github.com/vacuumlabs/ledgerjs-cardano-shelley) library and the fact that it seems you are not using the version that supports multisig. Are you sure you updated the yarn dependencies before building the tool?

**Comment by KubqoA** [comment]
It seems like the download for the `rc4` release of `ledgerjs-cardano-shelley` library changed it's name. I updated the branch to use `rc5` and now you should be able to build it. Can you please try again?

**Comment by gitmachtl** [comment]
yes, that worked. now also the cardano-app 3.0.0 is working with the hw-cli, thx!

```console
$ cardano-hw-cli version
Cardano HW CLI Tool version 1.8.0-rc0
Commit hash: 477ae160f0ff2a1515b1709d641f21e9047b58d3
```

**Comment by KubqoA** [comment]
Glad to hear that!
