### ISSUE TITLE
Keystone support

### ISSUE THREAD

**Issue by HeptaSean** [vacuumlabs/cardano-hw-cli#169]
Since Keystone now supports Cardano https://keyst.one/supported-wallets-and-assets?type=assets, it would be good if `cardano-hw-cli` could also work with it.

**Comment by janmazak** [comment]
Can you point us to some documentation on how to communicate with Keystone from typescript or javacript? And what kind of API does your firmware have for Cardano?

**Comment by janmazak** [comment]
Since Keystone seem to communicate only through QR codes, I'm not sure what integration with `cardano-hw-cli` would mean. Cardano-hw-cli is meant to be a simple command-line interface to HW wallets, with the sole purpose of getting signatures from them and writing them to a file. The signatures are then incorporated into transactions by using standard `cardano-cli`. Nothing to do with mobile phones, cameras or QR code scanning.

**Comment by HeptaSean** [comment]
To be honest: In this topic, I'm just a user not affiliated with Keystone.
I've used `cardano-hw-cli` with a Ledger in the past for token minting, for more elaborated Catalyst delegation setups, for all kinds of more complex transactions not supported by wallet apps.
If I now move most or all funds to a Keystone, I thought it would be a sensible question if that can also count as one of the `hw` in `cardano-hw-cli`.
The QR codes are just another, alternative communication channel, not inherently connected to mobile phones. In fact, I would *want* `cardano-hw-cli` (or maybe another tool) to write the witnesses to disk after decoding the QR codes received from the Keystone.
`catalyst-toolbox` for example does have some QR code generation and reading in a command line tool. So, it's not totally impossible.
But if it's too far away for you or the resources are not there for the foreseeable future, that's, of course, also okay.
