### ISSUE TITLE
Question - Extracting Staking Signing Key

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#18]
Hi,

would there be any chance to extract the staking signing key from the hw ledger if someone wants to do so?

Best regards, Martin

**Comment by refi93** [comment]
Hi @gitmachtl if you mean extracting the private key from Ledger, that's not possible for security reasons. Not 100% sure if it applies to Cardano's Ed25519 curve, but for other curves you should be even able to derive the parent private key once you have the child (non-hardened) private key and parent public key: https://bitcoin.stackexchange.com/questions/61478/determining-xprv-from-xpub-and-child-private-key

**Comment by gitmachtl** [comment]
Yes it is possible going thru the SeedPhrase... ok, but thx.

**Comment by refi93** [comment]
technically, Ledger uses a different process to obtain the root key from the seed than standard software wallets and currently there's no software wallet that would implement it: https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/CIP-0003.md but at the same time, obviously, exposing the mnemonic to a software wallet would defeat the security the Ledger device provides and you can as well have a staking key fully managed by the cli and pass it to Ledger in its raw form

**Comment by gitmachtl** [comment]
> and you can as well have a staking key fully managed by the cli and just pass it to Ledger in its raw form, which would at least ensure protection of your spending keys

can you elaborate on that? you mean generating the payment keys with Ledger but using the stakekey as before? hmm... not a bad idea, i have to test this. what do you mean by "pass it to Ledger in its raw form"?

**Comment by refi93** [comment]
yes, I mean managing payment key(s) on ledger and the staking one on the CLI. And then you just don't pass the respective staking hw signing key to the hw cli and Ledger should be able to sign the spending transaction just fine (as long as the tx does not perform at the same time certificate signatures/withdrawals as for those Ledger requires to have the staking key derivation path). You will also need to be careful with change addresses as Ledger will display them in their full form, since only the spending key was passed as a path

**Comment by gitmachtl** [comment]
i will test that, thx
