### ISSUE TITLE
Changing the hardware .vkey description field

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#29]
StakepoolOperatorScripts, CNtools and Jormanager have included the change to write out the hardware .vkey files with the Description:

`"Payment Hardware Verification Key"` for the payment key
`"Stake Hardware Verification Key"` for the stake key. 

It makes it much easier to check if a key is a cli or hardware one. As long as you're not saying that this is a major terrible idea, we'll keep it that way. :smiley:

_Originally posted by @gitmachtl in https://github.com/vacuumlabs/cardano-hw-cli/issues/27#issuecomment-751412976_

**Comment by refi93** [comment]
I would rather not do it natively at hw-wallet-cli level as the output format of the hw-wallet-cli is supposed to resemble the cardano-cli output as much as possible to ensure cross-compatibility with cardano-cli when assembling the transaction with its subcommands. Currently, the description likely does not play a role in cardano-cli, but it may in the future and this deviation may cause unnecessary compatibility issues.

I find it more sensible  to just use a different naming pattern for the hw cli keys - e.g. having a `.hw.vkey` extension for hardware wallet keys - that way hw verification keys would match "*.hw.vkey" expression and all keys regardless would be "*.vkey" - would such approach work for you?

**Comment by gitmachtl** [comment]
Well, i get your point, but shouldn't the `type` field be the important one for the tools? What sense does it make to have a description field when you can't use it as a free description? Its a standard JSON, so we could also add another key to mark it as a hardware key?

**Comment by refi93** [comment]
adding another field may cause compatibility issues if the validation of cardano-cli becomes more strict and would not allow JSONs with unknown fields which is a legitimate validation approach.

Altering the description field on cardano-hw-cli level is imho not worth it as it should be as simple as passing the files generated through "sed" or other similar tool and match a regex to replace it.

The `type` field needs to be kept consistent with cardano-cli, otherwise the `.vkey` files won't work with cardano-cli. Moreover, the `type` field really is about the cryptographic type of they key (ed25519) and that is the same for cardano-cli as well as cardano-hw-cli.

Another option may be having a flag to pass a custom description but that's not available at cardano-cli's level either and if we introduced our own version of it, cardano-cli may later on roll out their own variant, causing unnecessary ambiguity/confusion in cardano-cli vs cardano-hw-cli commands.

So there are at least two options to deal with the hw wallet backed keys without altering cardano-hw-cli which address the issue of distinguishing hw-cli keys from the cardano-cli ones:
1) use a regex to inject your own description/fields
2) use custom extensions to "tag" cardano-cli vkeys vs cardano-hw-cli keys

Both approaches should involve reasonably small effort when writing the scripts that handle the vkeys and do not introduce a maintainability burden into cardano-hw-cli as opposed to introducing custom logic into cardano-hw-cli. If there was a reasonable approach it may make sense to push for some additional field that would by adopted both by cardano-cli and cardano-hw-cli, but given the availablity of alternative approaches that work around this issue the benefits of such flag seem to outhweight the cons (backwards/forwards compatibility/maintainability both on cardano-cli and cardano-hw-cli side).

Do you see perhaps some conrete problem/paint point that wouldn't be addressed by the alternative approaches outlined above, that may justify the change?

**Comment by gitmachtl** [comment]
thx for your answer. yes the current implementation on how we did in on the major tools is to inject an own description in the description field like descripted in the first posting. i talked with samuel too, and currently the description field is not parsed in any way in cardano-cli. i thing we can live with that solution for now, if things change we will adopt 😄 

there is no need for you to change this in cardano-hw-cli.
