### ISSUE TITLE
upgrade txWitnesses type for allegra- and mary-era

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#31]
currently the signed witnesses are produced with shelley tag, this should be updated so that the witness is representing the current txBody era like:

| txBody<br>.type field| generated witness<br>.type field|
|     :---      |     :---     |
| `TxBodyMary` | `TxWitness MaryEra` |
| `TxBodyAllegra` | `TxWitness AllegraEra` |

even when you manually rename the type field in the witness for a witness in the mary era, it works fine. of course without any native assets in the transaction, that would fail. but cardano-cli witness assemble will fail if the eras are not the same.

**Comment by refi93** [comment]
@gitmachtl Hw wallets were developed for Shelley era and they don't support changes introduced in Mary/Allegra era yet. So changing the tx type would work only for tx bodies that actually don't differ across eras.

Aren't you able to build the transaction for shelley-era (which based on the changelog should still be the default: https://github.com/input-output-hk/cardano-node/releases - 1.24.2 "CLI changes")? If you depend on some Mary/Allegra-specific feature(s), those are unfortunately not supported yet by the hw wallets.

**Comment by gitmachtl** [comment]
Transactions in MaryEra are working fine with the Ledger as long as no Tokens are involved in the UTXO, because the backwards compatibility from Mary to Allegra and Shelley this makes sense. But the big question to me is the following: Will it be possible to include the Mary specific additional UTXO infos (not that much of a deal IMO) into a new firmware for the Hardware-Wallets later when Mary is on Mainnet!? Because you said "Hw Wallets were developed for Shelley era". If this could not be fixed with a FW update in the future, than using HW-Wallets for Pledge-Wallets or any Wallets at all would be a no go, because when someone sends you at least one native asset your funds will be locked up.

**Comment by refi93** [comment]
Regarding tokens support - yes, a fw update will address it. When I wrote the hw wallets were developed for Shelley era I meant that their latest firmwares were done with Shelley in mind, but of course, they are evolving as the Cardano eras progress and features are being added. We have no ETA for tokens yet but it's definitely high in our list of priorities. So you don't have to worry that the tokens won't be accessible from hw wallets at all, though it may take some time untill the respective update is rolled out, since it takes more time to develop and test it and it also goes through a longer reviewing/auditing process.

> Also you have to use the --build-raw command with cardano-cli in the same era the node is in, so for now you have to use --allegra-era. 

- if I understand correctly this means the cardano-cli/node just reject the tx body if it's era is not set to the respective node's era, so we'll likely need to extend cardano-hw-cli witnessing/tx signing command to accept the era and pass it to the witness JSON, implementing proper validation to avoid signing transactions that do not comply both with Shelley and Allegra/Mary era requirements while Ledger/Trezor gets updated - we will investigate that after holidays (Jan 6). Meanwhile, I'd suggest as a temporary workaround just overwriting the era in the tx body as you suggested in the issue

**Comment by gitmachtl** [comment]
thx for the response

**Comment by DavidTranDucVL** [comment]
Resolved in https://github.com/vacuumlabs/cardano-hw-cli/pull/33
