### ISSUE TITLE
Minimum cardano-app/fw version to go with as an SPO?

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#32]
Hi,

i tried to follow all discussions about the minimum firmware that is needed on the Ledger and Trezor devices to push the go button for mainnet usage of cardano-hw-cli and StakePool operation. I also saw your thread here (https://github.com/trezor/trezor-firmware/issues/1387) about the mnemonics problem with 24 seed words on Trezor. 

So, are we good to go with Ledger Cardano-App version 2.1.0 and upcoming Trezor fw version 2.3.5 or do we have any hold backs on this?

Ledger 2.1.0 is working fine on the TestNets so far, Trezor 2.3.4 is also working as i saw from others.

Thx!

Best regards, Martin

**Comment by refi93** [comment]
Hi @gitmachtl - Ledger Cardano app 2.1.0 and Trezor firmware 2.3.5 support stake pool registration only for the owners, so technically it's not full stake pool operator support, it's only a subset of the operations for the whole SPO use case. I'm not aware of any hold backs on that though. The respective app/firmware should be released in the first half of January 2021.

For Trezor it's probably worth mentioning that due to memory limitations it currently supports signing the stake pool registration for only up to approximately 20 owners and bigger transactions may result in a firmware error due to exhaustion of available memory, it's related to this issue: https://github.com/trezor/trezor-firmware/issues/998 - turned out after Shelley update the memory issues persisted though to a lesser extent, and we are still investigating how to optimize the memory usage.
