### ISSUE TITLE
Creating a transaction witness with Trezor Model T returns "Firmware error"

### ISSUE THREAD

**Issue by lcpaf** [vacuumlabs/cardano-hw-cli#39]
Creating a transaction witness with a Trezor Model T returns an error message: `Error: Firmware error`

Cardano-hw-cli version: `v1.1.1`
Carnode-cli version: `1.24.2`
Trezor Firmware version: `2.3.4`
OS: `Ubuntu 20.04.1`

I can provide more details about my environment, but I'm not quite sure what might be relevant.

**Comment by refi93** [comment]
Can you clarify what structure (count of inputs/outputs/certificates and their types/withdrwals) does your transaction have?

If you are trying a stake pool registration transaction, that's expected as Trezor fw 2.3.4 does not support that yet, it will support such transactions since version 2.3.5 which will be launched in February.

**Comment by lcpaf** [comment]
@refi93 that's exactly what I was trying to do. Thanks for the information. I will wait for version 2.3.5 to be launched.
