### ISSUE TITLE
Cannot witness a tx with a pool registration certificate using Trezor when "--pool-margin 0"

### ISSUE THREAD

**Issue by rootpool** [vacuumlabs/cardano-hw-cli#53]
If you create a pool registration certificate with `--pool-margin 0`, include it into a tx, when trying to witness the tx using a Trezor hw wallet, we get an `Invalid Certificate` error (both when using the AdaLite UI and CLI). 

The same scenario works with Ledger.

If we change the pool margin to `--pool-margin 0.0001`, everything is fine also with Trezor.

cc @refi93 (thank you for the prompt help with this)

**Comment by PeterBenc** [comment]
Hi thanks for the report, I cant really say when we ll release a fix on cli tool but I ll remember to fix it in upcoming release of adalite. I let you know.

**Comment by refi93** [comment]
Hi @rootpool - unfortunately, this is a validation bug at Trezor firmware's level, there is already a fix pull request pending on their repository and hopefully it will be fixed in the next release: https://github.com/trezor/trezor-firmware/pull/1502 Meanwhile the option is either using Ledger for such pool or setting a very low but nonzero margin for the pool.

**Comment by DavidTranDucVL** [comment]
This issue was resolved.
