### ISSUE TITLE
Clarify reward withdrawal when using hw wallet in docs

### ISSUE THREAD

**Issue by DanTup** [vacuumlabs/cardano-hw-cli#59]
In [these docs](https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/docs/poolRegistration.md) there is a section called "Create reward address". It's not clear to me how this relates to the hardware wallet or how the rewards are withdrawn.

Is this creating a new reward address, or the same one that delegation rewards would've gone to for the same hardware wallet (for example, will it match the one shown [in this AdaLite screenshot](https://miro.medium.com/max/4800/1*O92vx_vivig9UWxhhb7CtQ.png))? If it's producing a new address, what is the process from withdrawing the rewards? Would they show up in the same place as other rewards?

For example if I'm currently using AdaLite to withdraw my delegation rewards (before being an SPO) and I build a pool using these instructions (or more specifically, [using Adalite instead of cardano-hw-cli directly](https://adalite.medium.com/cardano-stake-pool-owners-hw-support-6d9278dba0ba)), can I continue to withdraw rewards through AdaLite or must this still be done using the CLI?

(Slight aside - of all the things [in this AdaLite screenshot](https://miro.medium.com/max/4800/1*O92vx_vivig9UWxhhb7CtQ.png), are any of them sensitive, or all essentially public? I couldn't find much info on the CBOR hex).

**Comment by refi93** [comment]
@DanTup answers to your questions:

> In these docs there is a section called "Create reward address". It's not clear to me how this relates to the hardware wallet or how the rewards are withdrawn.

The cli docs suggest that you can either manage your reward address from a hardware wallet or from standard cardano-cli. But arguably the simplest way to manage your reward address from a hw wallet and withdraw rewards is via a UI-based wallet such as Adalite which is completely fine. I just added that remark into the docs, thanks for raising this: https://github.com/vacuumlabs/cardano-hw-cli/commit/20cf842bbe0b832041bafe66986c12af9e110643

Another option to withdraw your rewards would be exporting the stake.vkey file in cardano-hw-cli and building the withdrawal transaction with standard cardano-cli as explained here: https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/withdraw-rewards.html - up to step `10.5. Build the raw transaction.`. Then you would go on to sign the built raw transaction with your hardware wallet as explained in cardano-hw-cli docs: https://github.com/vacuumlabs/cardano-hw-cli/blob/develop/docs/transaction-example.md#sign-the-transaction

> (Slight aside - of all the things in this AdaLite screenshot, are any of them sensitive, or all essentially public? I couldn't find much info on the CBOR hex).

The info shown there are just public keys or their hashes - most of it (everything except shelley extended public key chaincode, which is rather a technicality) gets published within the signed transaction when submitted, so it's not sensitive information. But of course, you may still want to not publish it in order to preserve your anonymity as a pool operator/owner.

**Comment by DanTup** [comment]
> But arguably the simplest way to manage your reward address from a hw wallet and withdraw rewards is via a UI-based wallet such as Adalite which is completely fine - protocol-wise Adalite does the same thing you would do with the cli. I just added that remark into the docs, thanks for raising this: 20cf842

Perfect - thanks for clarifying!

> so it's not sensitive information. But of course, you may still prefer to not publish it in order to preserve your anonymity as a pool operator/owner.

Great! I wasn't planning on publishing it, I'm just trying to make sure I fully understand what's critical to secure (my understanding was that the Ledger didn't let you access private keys directly, and it also seemed strange to copy/paste something sensitive from the AdaLite UI, so I was just checking my understanding is correct).

One final question (although not strictly about cardano-hw-cli) - if I follow the instructions above, using the staking information from AdaLite for both `--pool-owner-stake-verification-key-file` and `--pool-reward-account-verification-key-file`, the pledge and the SPO rewards are all protected with the hardware key. So if both the cold machine and the producer were compromised, the only things at risk are a) the 500 ADA deposit and b) control of the pool (eg. the rewards could be diverted elsewhere). No pledge or rewards (inc. those that have not been withdrawn) can be accessed from anything on either machine?

Ofc I don't intend either to be compromised, again I'm just trying to make sure I understand the risks. I couldn't find much detail on all of the specific files being generated and a) the implications of them being leaked or b) the implications of losing them.

Thank you for your responses!

**Comment by refi93** [comment]
@DanTup sorry for the delayed reply - provided the owners use hw wallets to register into the stake pool and the pool's reward address is controlled from a hw wallet as well, then basically as you've written, what's at risk when the cold machine is compromised are the deposit of 500 ADA (if the attacker deregisters the pool, though I'm not really sure if that deposit goes back to the original reward address of the pool or to the last one if the pool reward address gets updated meanwhile  - maybe @xdzurman can clarify) and subsequent control of the pool.

The owners' funds, rewards received so far and delegations would still be protected by their respective hw wallets

**Comment by DanTup** [comment]
@refi93 perfect - thanks for your detailed replies!

I'll close this, though I am curious about the answer to this question should anyone know :-)

> I'm not really sure if that deposit goes back to the original reward address of the pool or to the last one if the pool reward address gets updated meanwhile - maybe @xdzurman knows


Thanks!

**Comment by xdzurman** [comment]
Quoting "A Formal Specification of the Cardano Ledger":

```
The pool-reap transition rule is given in Figure 40. This transition has no preconditions and
results in the following state change:
• For each retiring pool, the refund for the pool registration deposit is added to the pool’s
registered reward account, provided the reward account is still registered.
• The sum of all the refunds attached to unregistered reward accounts are added to the
treasury
```

Therefore it's the currently registered reward account that all the rewards, deposits, etc., go to

**Comment by DanTup** [comment]
@xdzurman perfect, thanks!
