### ISSUE TITLE
Invalid data supplied to ledger

### ISSUE THREAD

**Issue by MMA-stakepool** [vacuumlabs/cardano-hw-cli#64]
Hi all,

is there a way to get more specific information on the error? I am trying to witness a transaction updating the pool's pledge and can't find what could be wrong. I manually checked that files' hashes match, the built transaction has correct fee and output, the pool certificate is also correct. Witnessing with non-hw cardano-cli works, my hw owner is blocking the transaction since it can't witness.
Is this a common issue and if not what else could I be doing wrong?

Thanks for reading and I hope you can help

**Comment by refi93** [comment]
Hi @MMA-stakepool - can you check what version of the Ledger cardano app and cardano-hw-cli is the owner using and make sure its the latest? The ledger app version should be 2.2.0 (possibly 2.2.1, both are fine) and cardano hw cli should be 1.2.0.

Regarding the error, such error usually (but not necessarily) happens if an older version of hw cli tries to communicate with a newer ledger app, so the first step would be to check that

Also please make sure the transaction contains only the registration alone and no other certificates/withdrawals, although standard validation should catch if this was the case.

Alternatively the owner can try using https://adalite.io which offers in the "advanced" tab an interface to load the files and should communicate properly with latest ledger app. It's described in this article: https://adalite.medium.com/cardano-stake-pool-owners-hw-support-6d9278dba0ba

**Comment by MMA-stakepool** [comment]
Thank you for your answer,

versions are 2.2.0 and 1.2.0, only one certificate in the transaction. I had 2 certificates before and was explicitly told to include only one as you said.
I will give adalite a go.

**Comment by MMA-stakepool** [comment]
I found the problem, since you said this happens with version conflicts I reinstalled cardano-hw-cli and it worked. It was telling me version 1.2.0 but probably still had files from the previous version.
