### ISSUE TITLE
question : Generate extended public key from known address

### ISSUE THREAD

**Issue by Mina-Farahat** [vacuumlabs/cardano-hw-cli#76]
Is it possible to generate the extended public key (1852'/1815'/0'/) if one of the derived keys are provided (i.e. (/1852'/1815'/0'/0/0), or (/1852'/1815'/0'/2/0)) ?

Also is it possible to generate the rest of the sub addresses if only one address is provide , i.e. generate /1852'/1815'/0'/0/1 using  /1852'/1815'/0'/0/0 ?

**Comment by DavidTranDucVL** [comment]
> Is it possible to generate the extended public key (1852'/1815'/0'/) if one of the derived keys are provided (i.e. (/1852'/1815'/0'/0/0), or (/1852'/1815'/0'/2/0)) ?

No

> Also is it possible to generate the rest of the sub addresses if only one address is provide , i.e. generate /1852'/1815'/0'/0/1 using /1852'/1815'/0'/0/0 ?

Also no

But in practical sense, if privacy is your concern: When you are creating a payment address it consists of two parts. The payment part and staking part. In which case, you would need for example:
- `/1852'/1815'/0'/0/0` AND `/1852'/1815'/0'/2/0 ` for payment address with index 0
- similarly, if you want payment address with index 1, you would need `/1852'/1815'/0'/0/1` AND `/1852'/1815'/0'/2/0 `
Because of the staking part `/1852'/1815'/0'/2/0 ` that is same for both, anybody can figure out and link together your addresses that are under this same stake key and see your total combined balance across whole account.

**Comment by Mina-Farahat** [comment]
Thanks a lot for your answer.
